# Generated by Django 5.0.3 on 2024-03-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_contactpagedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPageDetails',
            new_name='Contact',
        ),
    ]
