# Generated by Django 5.0.3 on 2024-03-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_contactpagedetails_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='position',
            new_name='title',
        ),
    ]
