# Generated by Django 5.0.3 on 2024-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_aboutpage_homepage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='contacts/%Y/%m/%d/'),
        ),
    ]
